### PR TITLE
add quality selection to m3u8 player

### PR DESCRIPTION
**Pull request by KenanY**
Closes https://github.com/MemeLabs/Rustla2/issues/174

image

### CODE REVIEW

**Comment by xDashh** [comment]
:tada:

**Comment by xDashh** [comment]
Just tested this and while it works under normal circumstances, it seems that it has problems working with the CORS proxy we use, so need to wait a bit to see if there is a solution for this.

**Comment by KenanY** [comment]
What problems in particular? I just tried it myself and didn't see any problems.

**Comment by xDashh** [comment]
Nevermind, was just testing-environment related problems...

**Pull request merged**
