### PR TITLE
Autoplay

### PR DESCRIPTION
**Pull request by jbpratt78**
Auto-playing services:
- Angelthump
- Dailymotion
- Chaturbate but muted
- Ustream
- Vaughn
- Youtube
- Youtube playlist

Not auto-playing due to various reasons
- Facebook
- Twitch

Removed:
- Azubu 
- Hitbox & Hitbox-vod
- Streamup
- MLG can work but dead platform so scraping. Only one stream live at the time of typing this.

Leaving Afreeca for now

### CODE REVIEW

**Comment by xDashh** [comment]
references (or closes)
https://github.com/MemeLabs/Rustla2/issues/22
https://github.com/MemeLabs/Rustla2/issues/66

**Comment by xDashh** [comment]
reminder to probably get rid of the volume param once this is being merged https://github.com/MemeLabs/Rustla2/pull/81/files#diff-ccf8a5cd91493c36de6fded1940cbf99R22

**Comment by KenanY** [comment]
Can you create a ticket for that?

**Comment by slugalisk** [comment]
@jbpratt78 These platforms are also validated by the backend. Could you update these lists too please? https://github.com/MemeLabs/Rustla2/blob/009435ed7683245a9c4ef16b6acbb19daa06ab5d/api/src/Channel.h#L16-L43

**Comment by jbpratt78** [comment]
@slugalisk Yeah I can do both of these @xDashh

**Comment by slugalisk** [comment]
@jbpratt78 It looks like your new revision replaced the frontend changes... You probably still have the previous revision locally (the hash was `ccf8a5cd91493c36de6fded1940cbf99R22`) so you should be able to rebase it onto your `autoplay` branch and push it to add it to the pr.

**Comment by slugalisk** [comment]
@jbpratt78 thanks 👍

**Pull request merged**
