### PR TITLE
make stream page and navbar responsive

### PR DESCRIPTION
**Pull request by KenanY**
This improves the mobile experience for the stream page and when using
the navbar.

Closes https://github.com/MemeLabs/Rustla2/issues/68
Closes https://github.com/MemeLabs/Rustla2/issues/142

### CODE REVIEW

**Comment by slugalisk** [comment]
the spacing between the right-most chat tab and the create stream form is missing. 


the responsive behavior for these doesn't make sense to me... they're not actions they're like a subtitle... in the mobile version of the layout could these collapse next to the title like 
```
Strims 11 / 29,282
```
or maybe add little comfy icon and a little npc icon or something?


this form layout is confusing... @xDashh how close are we to being able to ditch the manual platform picker for a simple stream page url input?

...i think the login button should be full width and have a text label and the whole thing should probably have more consistent spacing


if we're not going to allow users to resize the stream it should probably be fixed to a 16:9 aspect ratio since that's what almost all the content is. also chat seems broken in the responsive layout but not the standard layout...? i saw this same behavior whether i loaded the page in smol mode or resized after loading

**Comment by xDashh** [comment]
Regarding the manual platform picker, I'm still in favor of getting rid of that menu, and having a single text input textbox that does validation client-side (using if need be the copy pasted regexes from modbot). If no match it would maybe display an error box with a link of supported services.

**Comment by slugalisk** [comment]
i thought we could use regexes for known services and fall back to the m3u8 url discovery service?

**Comment by KenanY** [comment]
Second iteration:

  1. now maintaining 16:9 aspect ratio for the stream embed
  2. initial work on adding viewer counts to mobile navbar
  3. removed header form at mobile widths (at least for now)

TODO:

  - [ ] viewers counts need spacing between themselves
  - [ ] maybe some padding under last chat button option in the mobile menu
  - [ ] consider how to introduce the form on mobile
  - [ ] see if [`<ResponseEmbed>`](https://react-bootstrap.github.io/utilities/responsive-embed/) can be used for the stream embed instead of whatever CSS I came up with

---



---



---

**Comment by jbpratt78** [comment]
@KenanY what needs work on this PR? Xymos was trying this on his own before I showed him this so he can take over and finish it out if needed.

**Comment by KenanY** [comment]
Umm I'll need to revisit this to remind myself of what's left to do.

**Comment by KenanY** [comment]
Alright I checked this out locally again and it looks good to me as-is. Still no service/stream form nor login/profile button but we may be able to live without it on mobile for the time being.

**Comment by jbpratt78** [comment]
I think a login button should be implemented before we merge this, as users cannot login without manually navigating to the url. @KenanY would this be something you want to implement or maybe @x-Xymos can.

**Comment by KenanY** [comment]
Updated with login, logout, and profile links.

**Comment by jbpratt78** [comment]
> Updated with login, logout, and profile links.
> 
> 

Awesome, thank you!

**Comment by jbpratt78** [comment]
Awesome feature, thank you @KenanY

**Pull request merged**
